# Generated by Django 4.2.4 on 2023-08-19 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_loan_loan_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='loan_date',
            new_name='loan_type',
        ),
    ]
