# Generated by Django 4.2.3 on 2023-08-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_loan_loan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='original_return_date',
            field=models.DateField(null=True),
        ),
    ]
