# Generated by Django 4.2.3 on 2023-08-20 17:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_loan_original_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='original_return_date',
            field=models.DateTimeField(null=True),
        ),
    ]
